[package]
name = "ord_list_set"
version = "0.1.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ord_set_ops_iter = { path = "../ord_set_ops_iter" }
